language: node_js
node_js: lts/*

addons:
  ssh_known_hosts:
  - dev.riskopendata.org
  - index.opendri.org

install:
- cd frontend
- npm ci

test:
- export PYTHONPATH=$(realpath ./backend)
- cd frontend
- npm test
- npx semver --range $(< ./API_COMPATIBILITY) \
    $(python -c 'import ordd_api; print ordd_api.__version__;') \
    || (echo '/!\ Backend API and Frontend API are not compatible /!\' && exit 1)

before_deploy:
- cd $HOME/GFDRR/open-risk-data-dashboard
- openssl aes-256-cbc -K $encrypted_9245de407bbd_key -iv $encrypted_9245de407bbd_iv -in id_opendri.enc -out /tmp/id_opendri -d

deploy:
- provider: script
  script: rsync -e "ssh -i /tmp/id_opendri -p 22027" --delete-after -r ./frontend/
    cima@dev.riskopendata.org:~/html-dev/
  on:
    branch: master
