language: node_js
node_js: lts/*

install:
- cd frontend
- npm ci
test:
- cd frontend
- npm test

addons:
  ssh_known_hosts:
  - dev.riskopendata.org
  - index.opendri.org

deploy:
- provider: script
  script: rsync -e "ssh -p 22027" --delete-after -r ./frontend/ ${FRONTEND_SFTP_USER}@dev.riskopendata.org:~/html-dev/
  on:
    branch: master
# - provider: script
#   script: rsync -e "ssh -p 22" --delete-after -r ./frontend/ ${FRONTEND_SFTP_USER}@dev.riskopendata.org:~/html/
#   on:
#     branch: production
