[Settings]
ID = "index-opendri-preview"

[build]
  base = "frontend"
  command = "npm test"
  publish = "frontend"

[[redirects]]
  from = "/frontend/bower_components/*"
  to = "/bower_components/:splat"
