country_mapping = {
    "Bahamas, The": "Bahamas",
    "Cabo Verde": "Cape Verde",
    "Congo, Democratic Republic of": "Democratic Republic of the Congo",
    "Congo, Republic of": "Congo",
    "Cote d'Ivoire": "Côte d'Ivoire",
    "Curacao": "Netherlands Antilles",
    "Egypt, Arab Republic of": "Egypt",
    "Eswatini": "Swaziland",
    "French Southern Territories": "French Southern and Antarctic Territories",
    "Gambia, The": "Gambia",
    "Guernsey, C.I.": "Guernsey",
    "Heard and McDonald Islands": "Heard Island and McDonald Islands",
    "Holy See (Vatican City State)": "Holy See",
    "Hong Kong SAR, China": "Hong Kong",
    "Iran, Islamic Republic of": "Iran  (Islamic Republic of)",
    "Jersey, C.I.": "Jersey",
    "Korea, Democratic People's Republic of": "Dem People's Rep of Korea",
    "Korea, Republic of": "Republic of Korea",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Macao SAR, China": "Macau",
    "Macedonia, former Yugoslav Republic of": "The former Yugoslav Republic of Macedonia",
    "Micronesia, Federated States of": "Micronesia (Federated States of)",
    "Moldova": "Moldova, Republic of",
    "Reunion": "Réunion",
    "S. Georgia and S. Sandwich Islands": "South Georgia and the South Sandwich Islands",
    "Slovak Republic": "Slovakia",
    "St Maarten": "Netherlands Antilles",
    "St. Helena": "Saint Helena",
    "St. Kitts and Nevis": "Saint Kitts and Nevis",
    "St. Lucia": "Saint Lucia",
    "St. Pierre & Miquelon": "Saint Pierre et Miquelon",
    "St. Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Taiwan, China": "Taiwan",
    "Tanzania": "United Republic of Tanzania",
    "Turks and Caicos Islands": "Turks and Caicos islands",
    "United States": "United States of America",
    "Vietnam": "Viet Nam",
    "Virgin Islands, British": "United States Virgin Islands",
    "Virgin Islands, US": "British Virgin Islands",
    "Wallis and Futuna Islands": "Wallis and Futuna",
    "West Bank and Gaza": "West Bank",
    "Yemen, Republic of": "Yemen",
}
