# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='is_existing_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_machine_read_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_open_licence_txt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_prov_timely_last',
            field=models.TextField(blank=True),
        ),
    ]
