# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levresolution',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
