# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0002_remove_dataset_applicability'),
    ]

    def migrate_m2m_to_fk(apps, schema_editor):
        KeyTagGroup = apps.get_model("ordd_api", "KeyTagGroup")
        for keytaggroup in KeyTagGroup.objects.all():
            for tag in keytaggroup.tags.all():
                tag.group = keytaggroup
                tag.save()

    def migrate_fk_to_m2m(apps, schema_editor):
        KeyTag = apps.get_model("ordd_api", "KeyTag")
        for keytag in KeyTag.objects.all():
            if keytag.group:
                keytag.group.tags.add(keytag)
                keytag.group.save()

    operations = [
        migrations.AddField(
            model_name='keytag',
            name='group',
            field=models.ForeignKey(
                blank=True, default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ordd_api.KeyTagGroup'),
        ),
        migrations.RunPython(
            code=migrate_m2m_to_fk,
            reverse_code=migrate_fk_to_m2m,
        ),
        migrations.RenameField(
            model_name='keytaggroup',
            old_name='group',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='keytaggroup',
            name='tags',
        ),
        migrations.AlterField(
            model_name='keytag',
            name='group',
            field=models.ForeignKey(
                blank=True, default=None, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tags', to='ordd_api.KeyTagGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='keytag',
            unique_together=set([('group', 'name')]),
        ),
        migrations.AlterField(
            model_name='keytag',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags', to='ordd_api.KeyTagGroup'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tag',
            field=models.ManyToManyField(blank=True, to='ordd_api.KeyTag'),
        ),
    ]
