# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0002_char_to_text_on_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='is_avail_for_free',
            field=models.BooleanField(help_text='This question addresses whether the data is available for free or if there is a charge. If there is a charge, then that is stated in the comments section.', verbose_name='Is the data available for free?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_avail_online',
            field=models.BooleanField(help_text="This question addresses whether the data is available online from an official source. In the cases that this is answered with a 'yes', then the link is put in a URL field.", verbose_name='Is available Online?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_avail_online_meta',
            field=models.BooleanField(help_text="This question addresses whether the metadata is available online from an official source. In the cases that this is answered with a 'yes', then the link is put in a URL field.", verbose_name='Is the metadata available online?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_bulk_avail',
            field=models.BooleanField(help_text='Data is available in bulk if the whole dataset can be downloaded or accessed easily. Conversely it is considered non-bulk if the citizens are limited to just getting parts of the dataset (for example, if restricted to querying a web form and retrieving a few results at a time from a very large database).', verbose_name='Available in bulk?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_digital_form',
            field=models.BooleanField(help_text='This question addresses whether the data is in digital form (stored on computers or digital storage) or if it only in e.g. paper form.', verbose_name='Is data in digital form?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_existing',
            field=models.BooleanField(help_text='Does the data exist at all? The data can be in any form (paper or digital, offline or online etc). If it is not, then all the other questions are not answered.', verbose_name='Does the data exist?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_machine_read',
            field=models.BooleanField(help_text='Data is machine-readable if it is in a format that can be easily structured by a computer. Data can be digital but not machine-readable. For example, consider a PDF document containing tables of data. These are definitely digital but are not machine-readable because a computer would struggle to access the tabular information (even though they are very human-readable!). The equivalent tables in a format such as a spreadsheet would be machine-readable. Note: The appropriate machine-readable format may vary by type of data – so, for example, machine-readable formats for geographic data may be different than for tabular data. In general, HTML and PDF are not machine-readable.', verbose_name='Is the data machine-readable?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_open_licence',
            field=models.BooleanField(help_text='This question addresses whether the dataset is open as per http://opendefinition.org. It needs to state the terms of use or license that allow anyone to freely use, reuse or redistribute the data (subject at most to attribution or share alike requirements). It is vital that a licence is available (if there is no licence, the data is not openly licensed). Open licences which meet the requirements of the Open Definition are listed at http://opendefinition.org/licenses/.', verbose_name='Openly licensed?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_prov_timely',
            field=models.BooleanField(help_text='This question addresses whether the data is up to date and timely - or long delayed. For example, for census data that it is made available soon after the census is performed or if it is only available many years later. Any comments around uncertainty are put in the comments field.', verbose_name='Is the data provided on a timely and up to date basis?'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_pub_available',
            field=models.BooleanField(help_text='This question addresses whether the data is "public". This does not require it to be freely available, but does require that someone outside of the government can access it in some form (examples include if the data is available for purchase, if it exists as a PDF on a website that you can access, if you can get it in paper form - then it is public). If a freedom of information request or similar is needed to access the data, it is not considered public.', verbose_name='Publicly available?'),
        ),
    ]
