# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0003_auto_20170807_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='thinkhazard_appl',
            field=models.ManyToManyField(to='ordd_api.KeyPeril'),
        ),
    ]
