# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    KeyTag = apps.get_model("ordd_api", "KeyTag")
    db_alias = schema_editor.connection.alias
    for tag in KeyTag.objects.using(db_alias).all():
        if tag.group.name == 'hazard':
            tag.is_peril = True
            tag.save()


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0004_country_thinkhazard_appl'),
    ]

    operations = [
        migrations.AddField(
            model_name='keytag',
            name='is_peril',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
