# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0006_auto_20170811_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='thinkhazard_appl',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='thinkhazard_appl_tag',
            new_name='thinkhazard_appl',
        ),
        migrations.RemoveField(
            model_name='keydataset',
            name='applicability',
        ),
        migrations.RenameField(
            model_name='keydataset',
            old_name='applicability_tag',
            new_name='applicability',
        ),
    ]
