# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0007_replace_peril_fields_with_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyPeril',
            new_name='KeyPerilObsolete',
        ),
    ]
