# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0008_auto_20170814_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
