# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0010_content_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='is_existing_txt',
            field=models.TextField(blank=True, verbose_name="Comments on 'Does the data exist?'"),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_machine_read_txt',
            field=models.TextField(blank=True, verbose_name="Comments on 'is the data machine-readable?'"),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='is_open_licence_txt',
            field=models.TextField(blank=True, verbose_name="Comments on: 'Openly licensed?'"),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes about dataset'),
        ),
        migrations.AlterField(
            model_name='keydataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keydatasets', to='ordd_api.KeyDatasetName'),
        ),
    ]
