# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0011_auto_20170906_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='optin',
            name='insert_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
