# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:50
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
import os
import subprocess


def forwards_func(apps, schema_editor):
    name = os.path.join(os.path.dirname(__file__), 'load_content_script.py')
    sub = subprocess.run(['python3', name])
    if sub.returncode != 0:
        raise ValueError('load_content_script.py return [%d]' % sub.returncode)

    call_command('', verbosity=0, interactive=False)
    call_command('load_countries', '--filein',
                 'contents/countries/ordd_countries_list_iso3166.csv',
                 verbosity=0, interactive=False)
    call_command('load_key_datasets', '--reload', '--filein',
                 'contents/key_datasets/kd-categories.csv',
                 'contents/key_datasets/kd-tags.csv',
                 'contents/key_datasets/kd-datasets.csv',
                 verbosity=0, interactive=False)
    call_command('load_thinkhazard', '--datapath',
                 './contents/thinkhazard/cache',
                 verbosity=0, interactive=False)


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0012_optin_insert_time'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
