# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:50
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0012_optin_insert_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydataset',
            name='description',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
