# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0018_dataset_change_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=4096, unique=True),
        ),
    ]
