# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:50
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
import django.conf as conf
import os
import subprocess


def forwards_func(apps, schema_editor):
    database_name = conf.settings.DATABASES['default']['NAME']
    print("\n%s DBNAME [%s]\n" % (
        __file__, database_name))
    call_command('load_thinkhazard2018', '--datapath',
                 './contents/thinkhazard/cache',
                 verbosity=0, interactive=False)


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0020_countries2018'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
