# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0021_thinkhazard2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='wb_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
