# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:50

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Country = apps.get_model("ordd_api", "Country")
    countries = Country.objects.using(db_alias).all()

    for country in countries:
        country.wb_id = country.iso2
        country.save()


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0022_country_wb_id_schema'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
