# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0022_prepare_region_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='country',
            name='country_group',
            field=models.ManyToManyField(to='ordd_api.CountryGroup'),
        ),
    ]
