# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 11:50
from __future__ import unicode_literals
import csv

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Country = apps.get_model("ordd_api", "Country")
    CountryGroup = apps.get_model("ordd_api", "CountryGroup")

    db_alias = schema_editor.connection.alias

    CountryGroup.objects.using(db_alias).all().delete()

    with open('contents/countries/country_groups.csv',
              'r') as country_groups_f:
        next(country_groups_f)
        country_groups_csv = csv.reader(country_groups_f,
                                        delimiter=',')
        for country_group in country_groups_csv:
            cg_name = country_group[0]
            print("Country group: '%s'" % cg_name)
            cg_wb_id = country_group[1]
            cg_country_ids = country_group[2:]

            country_group = CountryGroup.objects.using(db_alias).create(
                wb_id=cg_wb_id, name=cg_name)
            country_group.save()

            for country_id in cg_country_ids:
                if country_id == '':
                    continue
                country = Country.objects.using(db_alias).get(
                    iso2=country_id)
                print("  Country: '%s'" % country.name)
                country_group.country.add(country)


def backwards_func(apps, schema_editor):
    CountryGroup = apps.get_model("ordd_api", "CountryGroup")

    db_alias = schema_editor.connection.alias

    CountryGroup.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0023_region_to_country_groups_schema'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
