# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0025_dataset_country_wb_id_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='thinkhazard_appl',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='country',
        ),
        migrations.AlterField(
            model_name='country',
            name='wb_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
