# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-19 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0028_dataset_country_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='country_wb_id',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordd_api.Country'),
        ),
    ]
