# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0029_rm_construction_stuff_and_enabled_country_key_constr'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='thinkhazard_appl',
            field=models.ManyToManyField(to='ordd_api.KeyTag'),
        ),
    ]
