# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordd_api', '0032_prepare_region_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('wb_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='countrygroup',
            name='country',
            field=models.ManyToManyField(to='ordd_api.Country'),
        ),
    ]
